server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: false  # 我们使用的是hostname注册，要设置为false，否则注册不成功
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka,http://eureka-2.eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
