server:
  port: ${PORT:8092}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_SERVER:https://github.com/caoping6/config-demo.git}
          label: master
          search-paths: config-repo
          clone-on-start: true # 开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-0:8761/eureka,http://eureka-1:8761/eureka,http://eureka-2:8761/eureka}